In [1]:
import pandas as pd
import numpy as np
import sys
import torch.nn as nn
import torch
from sklearn.model_selection import train_test_split

df = pd.read_csv('data/train.csv')

X_train, X_test, y_train, y_test = train_test_split(df.text,df.target,test_size=0.3,random_state=42, shuffle=True)

X_train.shape[0], X_test.shape[0], y_train.shape[0], y_test.shape[0]


C:\Users\Daniel\AppData\Local\Temp\ipykernel_24268\488755462.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


(5329, 2284, 5329, 2284)

In [2]:


# # Assuming df is your DataFrame containing the tweets
# # Create the vocabulary

# vocabulary = np.array([])
# for i in range(len(df.index)):
#     words = df['text'].iloc[i].split()  
#     vocabulary = np.append(vocabulary, np.unique(words))  
#     vocabulary = np.unique(vocabulary)

# # Create a dictionary to map each word to an index
# word_to_index = {word: idx for idx, word in enumerate(vocabulary)}

# # Function to one-hot encode a tweet
# def one_hot_encode(tweet, vocab_size):
#     one_hot_vector = np.zeros(vocab_size)
#     for word in tweet.split():
#         if word in word_to_index:
#             index = word_to_index[word]
#             one_hot_vector[index] = 1
#     return one_hot_vector

# # Apply the one-hot encoding to each tweet
# one_hot_encoded_tweets = np.array([one_hot_encode(tweet, len(vocabulary)) for tweet in df['text']])

# # Convert to DataFrame for better readability (optional)
# one_hot_encoded_df = pd.DataFrame(one_hot_encoded_tweets, columns=vocabulary)

# print(one_hot_encoded_df.columns)

In [3]:
one_hot_encoded_df = pd.read_csv("data/one_hot_encoded_df.csv")

In [4]:
# sys.getsizeof(one_hot_encoded_df)

In [5]:
all_categories = [1,0]
n_letters = one_hot_encoded_df.shape[1]
n_letters

31925

In [6]:
def letterToIndex(letter):
    return one_hot_encoded_df.columns.get_loc(letter)

def lineToTensor(line):
    line = line.split()
    # We want to have a tensor that, in the first dimension has the sequence index
    # 2nd dimension idk
    # 3d dimension for the one hot element

    # Create empty tensor
    tensor = torch.zeros(len(line), n_letters)

    # Create the sequence tensor
    for li, letter in enumerate(line):
        # print(letterToIndex(letter))
        tensor[li][letterToIndex(letter)] = 1

    return tensor


def categoryFromOutput(output):
    top_n, top_i = output.topk(1)
    category_i = top_i[0].item()
    return all_categories[category_i], category_i


In [7]:

letterToIndex(df.text.iloc[10].split()[0])
print(df.text.iloc[10].split())

one_hot_encoded_df

['Three', 'people', 'died', 'from', 'the', 'heat', 'wave', 'so', 'far']


Unnamed: 0    !   !!  !!!  !!!!  !!!!!  !!!!!!!!!!!#MetroFmTalk  !The  \
0              0  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
1              1  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
2              2  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
3              3  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
4              4  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
...          ...  ...  ...  ...   ...    ...                      ...   ...   
1141        1141  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
1142        1142  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
1143        1143  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
1144        1144  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   
1145        1145  0.0  0.0  0.0   0.0    0.0                      0.0   0.0   

        #  ##book  ...  å£9!  å¤}   å¨  å©Daniel  å¬'Only   åÇ   åÈ  \
0     0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
1     0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
2     0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
3     0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
4     0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
...   ...     ...  ...   ...  ...  ...       ...      ...  ...  ...   
1141  0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
1142  0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
1143  0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
1144  0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   
1145  0.0     0.0  ...   0.0  0.0  0.0       0.0      0.0  0.0  0.0   

      åÈMGN-AFRICAå¨   åÊ  åÊFedEx  
0                0.0  0.0      0.0  
1                0.0  0.0      0.0  
2                0.0  0.0      0.0  
3                0.0  0.0      0.0  
4                0.0  0.0      0.0  
...              ...  ...      ...  
1141             0.0  0.0      0.0  
1142             0.0  0.0      0.0  
1143             0.0  0.0      0.0  
1144             0.0  0.0      0.0  
1145             0.0  0.0      0.0  

[1146 rows x 31925 columns]

In [8]:
dataset_tensor_list = []
target_list=[]
import random
category = 1

# Convertir cada tensor a 
for i in  df.index:
    # Convert to tensor
    # print(i)
    line_tensor = lineToTensor(df.text.iloc[i])
    category_tensor = torch.tensor([all_categories.index(category)], dtype=torch.long)
    dataset_tensor_list.append(line_tensor)
    target_list.append(category_tensor)


sys.getsizeof(dataset_tensor_list)

67224

In [24]:
import torch

tensor_to_stack = torch.zeros(1000,1,31925)



In [19]:
dataset_tensor_list1 = dataset_tensor_list[0:1000]
dataset_tensor_list2 = dataset_tensor_list[1000:2000]

Padded Tensor 1:
 tensor([[1, 2, 3]])
Padded Tensor 2:
 tensor([[4, 5, 0]])

Joined Tensor:
 tensor([[1, 2, 3],
        [4, 5, 0]])


In [38]:
padded_dataset2.shape

padded_dataset2 = torch.cat([padded_dataset2, tensor_to_stack],dim=1)


In [40]:
padded_dataset2.shape

torch.Size([1000, 31, 31925])

In [23]:
len(dataset_tensor_list)

padded_dataset1.shape
padded_dataset2.shape



torch.Size([1000, 30, 31925])

In [31]:
torch.sum(padded_dataset1[9],dim=(1))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
import torch
from torch.nn.utils.rnn import pad_sequence


# Ensure all tensors in dataset_tensor_list have the shape [seq_len, 1, n_letters]
# Pad sequences to the maximum length in the batch
padded_dataset1 = pad_sequence(dataset_tensor_list1, batch_first=True)
padded_dataset2 = pad_sequence(dataset_tensor_list2, batch_first=True)
# padded_dataset = pad_sequence(dataset_tensor_list, batch_first=True)


padded_dataset1.shape, padded_dataset2.shape

(torch.Size([1000, 31, 31925]), torch.Size([1000, 30, 31925]))

In [12]:
torch.sum(dataset_tensor_list1[0])
dataset_tensor_list1[0].shape

torch.Size([13, 31925])

In [13]:
padded_dataset1[0]

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [14]:
sys.getsizeof(padded_dataset1)

80

In [15]:
# If using in RNN, you need lengths to pack the sequence (if applicable)
sequence_lengths = torch.tensor([tensor.size(0) for tensor in dataset_tensor_list])

# (Optional) Pack the sequence, if used in an RNN
packed_dataset = torch.nn.utils.rnn.pack_padded_sequence(padded_dataset, sequence_lengths, batch_first=True, enforce_sorted=False)


NameError: name 'padded_dataset' is not defined

In [119]:
padded_dataset1.shape

torch.Size([100, 27, 31925])

In [21]:
# sys.getsizeof(padded_dataset.shape)

torch.save(padded_dataset1, 'padded_dataset1.pt')

In [112]:
# import pickle
# with open("padded_dataset1.pkl", "wb") as file:
#     pickle.dump(padded_dataset1, file)

In [61]:
len(dataset_tensor_list)

from torch.utils.data import TensorDataset

TensorDataset(dataset_tensor_list,target_list)

AttributeError: 'list' object has no attribute 'size'